DOMAIN = "smart_offset_thermostat"
PLATFORMS = ["sensor", "climate", "switch", "button"]

CONF_CLIMATE = "climate_entity"
CONF_ROOM_SENSOR = "room_sensor_entity"
CONF_ROOM_TARGET = "room_target"
CONF_INTERVAL_SEC = "interval_sec"
CONF_DEADBAND = "deadband"
CONF_STEP_MAX = "step_max"
CONF_STEP_MIN = "step_min"
CONF_LEARN_RATE = "learn_rate"
CONF_TRV_MIN = "trv_min"
CONF_TRV_MAX = "trv_max"
CONF_COOLDOWN_SEC = "cooldown_sec"
CONF_ENABLE_LEARNING = "enable_learning"

DEFAULT_INTERVAL_SEC = 240
DEFAULT_DEADBAND = 0.2
DEFAULT_STEP_MAX = 1.0
DEFAULT_STEP_MIN = 0.5
DEFAULT_LEARN_RATE = 0.05
DEFAULT_TRV_MIN = 12.0
DEFAULT_TRV_MAX = 30.0
DEFAULT_COOLDOWN_SEC = 600
DEFAULT_ENABLE_LEARNING = True

DEFAULTS = {
    CONF_ROOM_TARGET: 22.0,
    CONF_INTERVAL_SEC: DEFAULT_INTERVAL_SEC,
    CONF_DEADBAND: DEFAULT_DEADBAND,
    CONF_STEP_MAX: DEFAULT_STEP_MAX,
    CONF_STEP_MIN: DEFAULT_STEP_MIN,
    CONF_LEARN_RATE: DEFAULT_LEARN_RATE,
    CONF_TRV_MIN: DEFAULT_TRV_MIN,
    CONF_TRV_MAX: DEFAULT_TRV_MAX,
    CONF_COOLDOWN_SEC: DEFAULT_COOLDOWN_SEC,
    CONF_ENABLE_LEARNING: DEFAULT_ENABLE_LEARNING,
}

SIGNAL_UPDATE = "smart_offset_thermostat_update"


CONF_WINDOW_SENSOR = "window_sensor_entity"
CONF_WINDOW_SENSORS = "window_sensor_entities"
CONF_BOOST_DURATION_SEC = "boost_duration_sec"

DEFAULT_BOOST_DURATION_SEC = 300

DEFAULTS.update({
    CONF_BOOST_DURATION_SEC: DEFAULT_BOOST_DURATION_SEC,
})

CONF_STUCK_ENABLE = "stuck_enable"
CONF_STUCK_SECONDS = "stuck_seconds"
CONF_STUCK_MIN_DROP = "stuck_min_drop"
CONF_STUCK_STEP = "stuck_step"

DEFAULT_STUCK_ENABLE = True
DEFAULT_STUCK_SECONDS = 1800
DEFAULT_STUCK_MIN_DROP = 0.10
DEFAULT_STUCK_STEP = 0.5

DEFAULTS.update({
    CONF_STUCK_ENABLE: DEFAULT_STUCK_ENABLE,
    CONF_STUCK_SECONDS: DEFAULT_STUCK_SECONDS,
    CONF_STUCK_MIN_DROP: DEFAULT_STUCK_MIN_DROP,
    CONF_STUCK_STEP: DEFAULT_STUCK_STEP,
})
